baseURL = "https://dario.dev.br/"
title = "Dario Camargo"
pagination.pagerSize = 3
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
# sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
logo = "images/rice.svg"
palette = "base16-dark"
header_text = "dario.dev.br"

[languages.en]
  label = "English"
  locale = "en"
  weight = 1

  [languages.en.params.boot]
    [[languages.en.params.boot.lines]]
      text = "Started Software Engineer."

    [[languages.en.params.boot.lines]]
      text = "Loaded kernel modules: Go, Java, Python."

    [[languages.en.params.boot.lines]]
      text = "Reached target Distributed Systems."

    [[languages.en.params.boot.lines]]
      text = "Reached target Reliability Engineering."

    [[languages.en.params.boot.lines]]
      text = "Mounted Control & Automation Engineering."

    [[languages.en.params.boot.lines]]
      text = "Mounted Go Expert (Full Cycle)."

    [[languages.en.params.boot.lines]]
      text = "Mounted Java Architecture and Development (FIAP)."

[languages.pt]
  label = "Português"
  locale = "pt-BR"
  weight = 2

  [languages.pt.params.boot]
    [[languages.pt.params.boot.lines]]
      text = "Iniciado: Engenheiro de Software."

    [[languages.pt.params.boot.lines]]
      text = "Módulos do kernel carregados: Go, Java, Python."

    [[languages.pt.params.boot.lines]]
      text = "Alvo alcançado: Sistemas Distribuídos."

    [[languages.pt.params.boot.lines]]
      text = "Alvo alcançado: Engenharia de Confiabilidade."

    [[languages.pt.params.boot.lines]]
      text = "Montado: Engenharia de Controle e Automação."

    [[languages.pt.params.boot.lines]]
      text = "Montado: Go Expert (Full Cycle)."

    [[languages.pt.params.boot.lines]]
      text = "Montado: Arquitetura e Desenvolvimento Java (FIAP)."

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "boot"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "whoami"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "til"
    name = "TIL"
    url = "/til/"
    weight = 20



[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.highlight]
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true

[taxonomies]
  tag = "tags"
  category = "categories"