baseURL = "https://dario.dev.br/"
title = "Dario Camargo"
pagination.pagerSize = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
# sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
logo = "images/rice.svg"
palette = "base16-dark"
header_text = "dario.dev.br"
branch = "main"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/dpcamargo"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "LinkedIn"
url = "https://linkedin.com/in/dpcamargo"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "til"
    name = "TIL"
    url = "/til/"
    weight = 20



[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true

[taxonomies]
  tag = "tags"
  category = "categories"